import type { PagesJson } from '@uni-ku/pages-json/types';
import type { UniPlatform } from './utils/uni-env';
import fs from 'node:fs';
import { join } from 'node:path';
import { checkFile } from './utils/file';

function generateDeclaration(jsons: Record<UniPlatform, PagesJson>) {

  const subPagePaths = new Set<string>();
  const tabPaths = new Set<string>();
  const pagePaths = new Set<string>();

  for (const [, pagesJson] of Object.entries(jsons)) {
    for (const sub of (pagesJson.subPackages || [])) {
      for (const page of (sub.pages || [])) {
        subPagePaths.add(`"/${join(sub.root!, page.path).replaceAll('\\', '/')}"`);
      }
    }

    for (const tab of (pagesJson.tabBar?.list || [])) {
      tabPaths.add(`"/${tab.pagePath}"`);
    }

    for (const page of (pagesJson.pages || [])) {
      const path = `"/${page.path}"`;
      if (!tabPaths.has(path)) {
        pagePaths.add(path);
      }
    }
  }

  const code = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @uni-ku/pages-json

interface NavigateToOptions {
  url: ${[...pagePaths, ...subPagePaths].join(' |\n       ')};
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  ${tabPaths.size ? `url: ${[...tabPaths].join(' |\n       ')};` : ''}
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
`;
  return code;
}

export async function writeDeclaration(jsons: Record<UniPlatform, PagesJson>, filepath: string) {

  const ok = await checkFile ({ path: filepath, newContent: '', modeFlag: fs.constants.W_OK | fs.constants.R_OK });
  if (!ok) {
    return;
  }

  const originalContent = await fs.promises.readFile(filepath, 'utf-8').catch(() => '');

  const code = generateDeclaration(jsons);
  if (!code) {
    return;
  }

  if (code !== originalContent) {
    await fs.promises.writeFile(filepath, code);
  }
}
