import type { PagesJson } from '@uni-ku/pages-json/types';
import fs from 'node:fs';
import { join } from 'node:path';
import { checkFile } from './utils/file';

function generateDeclaration(pagesJson: PagesJson) {
  const subPagesPaths = (pagesJson.subPackages || []).map((sub) => {
    return (sub.pages || []).map(v => (`"/${join(sub.root!, v.path).replaceAll('\\', '/')}"`));
  }).flat();
  const tabPaths = (pagesJson.tabBar?.list || []).map((v) => {
    return `"/${v!.pagePath}"`;
  });
  const allPagesPath = [...(pagesJson.pages || []).filter(page => !tabPaths.includes(page.path)).map(v => `"/${v.path}"`), ...subPagesPaths];
  const code = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @uni-ku/pages-json

interface NavigateToOptions {
  url: ${allPagesPath.join(' |\n       ')};
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  ${tabPaths.length ? `url: ${tabPaths.join(' |\n       ')};` : ''}
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
`;
  return code;
}

export async function writeDeclaration(pagesJson: PagesJson, filepath: string) {

  const ok = await checkFile ({ path: filepath, newContent: '', modeFlag: fs.constants.W_OK | fs.constants.R_OK });
  if (!ok) {
    return;
  }

  const originalContent = await fs.promises.readFile(filepath, 'utf-8').catch(() => '');

  const code = generateDeclaration(pagesJson);
  if (!code) {
    return;
  }

  if (code !== originalContent) {
    await fs.promises.writeFile(filepath, code);
  }
}
