name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 构建并发版
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 获取当前和上一个标签
        id: get_tags
        run: |
          git fetch --prune --unshallow
          tags=($(git tag -l --sort=-committerdate));
          current_tag=${tags[0]};
          previous_tag=${tags[1]};
          echo "previous_tag=$previous_tag" >> $GITHUB_OUTPUT
          echo "current_tag=$current_tag" >> $GITHUB_OUTPUT

      - name: 提取并分类提交消息
        id: extract_commit_messages
        run: |
          set -e
          current_tag="${{ steps.get_tags.outputs.current_tag }}"
          previous_tag="${{ steps.get_tags.outputs.previous_tag }}"
          if [ -z "$previous_tag" ]; then
            commit_messages=$(git log --pretty=format:"%s - by @%an (%h)" "$current_tag" | grep -E 'feat|fix|docs|perf|refactor' || true)
          else
            commit_messages=$(git log --pretty=format:"%s - by @%an (%h)" "$previous_tag".."$current_tag" | grep -E 'feat|fix|docs|perf|refactor' || true)
          fi

          # 转义 ` 字符
          commit_messages=$(echo "$commit_messages" | sed 's/`/\\\`/g')

          {
            echo 'feat_messages<<EOF'
            echo "$commit_messages" | grep 'feat' || true
            echo 'EOF'
          } >> $GITHUB_OUTPUT
          {
            echo 'fix_messages<<EOF'
            echo "$commit_messages" | grep 'fix' || true
            echo 'EOF'
          } >> $GITHUB_OUTPUT
          {
            echo 'docs_messages<<EOF'
            echo "$commit_messages" | grep 'docs' || true
            echo 'EOF'
          } >> $GITHUB_OUTPUT
          {
            echo 'perf_messages<<EOF'
            echo "$commit_messages" | grep 'perf' || true
            echo 'EOF'
          } >> $GITHUB_OUTPUT
          {
            echo 'refactor_messages<<EOF'
            echo "$commit_messages" | grep 'refactor' || true
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: 获取当前分支名
        id: get_branch_name
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT

      - name: 发版详情
        id: generate_release_notes
        run: |
          # 提取提交消息分类
          feat_messages=("${{ steps.extract_commit_messages.outputs.feat_messages }}")
          fix_messages=("${{ steps.extract_commit_messages.outputs.fix_messages }}")
          docs_messages=("${{ steps.extract_commit_messages.outputs.docs_messages }}")
          perf_messages=("${{ steps.extract_commit_messages.outputs.perf_messages }}")
          refactor_messages=("${{ steps.extract_commit_messages.outputs.refactor_messages }}")

          release_notes=""

          if [[ -n "$feat_messages" ]]; then
            release_notes="$release_notes\n### 🚀 Features 新功能:  \n"
            while IFS= read -r message; do
              release_notes="$release_notes\n- $message"
            done <<< "$feat_messages"
          fi

          if [[ -n "$fix_messages" ]]; then
            release_notes="$release_notes\n### 🩹 Fixes 缺陷修复:  \n"
            while IFS= read -r message; do
              release_notes="$release_notes\n- $message"
            done <<< "$fix_messages"
          fi

          if [[ -n "$docs_messages" ]]; then
            release_notes="$release_notes\n### 📖 Documentation 文档:  \n"
            while IFS= read -r message; do
              release_notes="$release_notes\n- $message"
            done <<< "$docs_messages"
          fi

          if [[ -n "$perf_messages" ]]; then
            release_notes="$release_notes\n### 🔥 Performance 性能优化:  \n"
            while IFS= read -r message; do
              release_notes="$release_notes\n- $message"
            done <<< "$perf_messages"
          fi

          if [[ -n "$refactor_messages" ]]; then
            release_notes="$release_notes\n### ♻️ Refactors 重构:  \n"
            while IFS= read -r message; do
              release_notes="$release_notes\n- $message"
            done <<< "$refactor_messages"
          fi

          # 转义 ` 字符
          release_notes=$(echo "$release_notes" | sed 's/`/\\\`/g')
          echo "release_notes=$release_notes" >> $GITHUB_OUTPUT

      - name: 写入生成的发布说明到 changelog.md
        run: |
          echo -e "${{ steps.generate_release_notes.outputs.release_notes }}" > changelog.md
          cat changelog.md

      - name: 引用 changelog.md 创建发版
        id: release_tag
        uses: ncipollo/release-action@v1.14.0
        with:
          bodyFile: changelog.md

  publish:
    name: 发布到 NPM
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      actions: write
      pull-requests: write
      statuses: write
      contents: write
      issues: write
      security-events: write
      pages: read

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 PNPM
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 10
          run_install: false

      - name: 配置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: 安装依赖
        run: pnpm i --frozen-lockfile

      - name: 打包
        run: pnpm build

      - name: 发布到 NPM
        run: pnpm publish --access=public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
